#+TITLE:CS 306 Syllabus and Portfolio@@html:<br>@@ Spring 2019
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t ':t d:(not "HINT")
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty
#+SETUPFILE: theme-bigblow.setup

:HINT:
 Click your mouse on the link below, or with your cursor somewhere in it, press
 the Enter key.
 [[elisp:(browse-url-of-file%20(org-html-export-to-html))][Export to HTML and Browse]]
:END:

* What\rsquo{}s It All About?
  This course is about *algorithms and complexity*.

* Objectives
  - Become conversant with the topics and issues surrounding
    algorithms and complexity. These include (but are not limited to):
    - Basic algorithms analysis: Asymptotic analysis of upper and
      average complexity bounds;
    - Best, average, and worst case behaviors;
    - Big-Oh, little-Oh, Big-Omega, and Big-Theta notation;
    - Standard complexity classes;
    - Empirical measurements of performance; time and space tradeoffs
      in algorithms;
    - Using recurrence relations to analyze recursive algorithms;
    - Fundamental algorithmic strategies: brute-force; greedy; divide
      and conquer; decrease and conquer; backtracking;
    - Graph and tree algorithms: depth-and-breadth-first traversals;
      shortest-path (Dijkstra\rsquo{}s and Floyd\rsquo{}s algorithms); minimum
      spanning tree (Prim\rsquo{}s and Kruskal\rsquo{}s algorithms); topological
      sort.

  - Learn the techniques (i.e., acquire the "tools").
    - Analyze and compare algorithms using Big-Oh, Big-Omega, and
      Big-Theta.
    - Describe and implement in a high-level language (e.g., lisp)
      some or all of the following algorithmic techniques: Brute
      Force, Divide/Decrease/Transform-and-Conquer, Greedy, Dynamic
      Programming, Iterative Improvement and Backtracking.
* Prerequisites
  You must have successfully completed the following courses:

  - CS 235 Data Structures
  - CS 237 Discrete Mathematics I

  You must have *some* working knowledge of:

   - Procedural, Object-Oriented, and Functional Programming
   - Basic data structures (sets, lists, maps, trees, graphs, etc.)
   - Summation notation (\Sigma)
   - Recurrence relations
   - Limits
   - Logarithms
   - Matrices
* Requirements
  You are required to:
  + attend class each class period (but then again, why wouldn\rsquo{}t you?);
  + read assigned portions of the course materials /before/ the class meeting
    when they will be discussed;
  + complete weekly preparation assessments; and
  + do weekly homework assignments to deepen your understanding of selected
    topics.

** Required Text

   /Introduction to the Design and Analysis of Algorithms/

   *Anany Levitin*

   /Third Edition, 2012, Pearson/

   ISBN: 9780132316811

** Required Software
  To install these tools, see the instructions [[https://rickneff.github.io][here]] (and go to the /Tools/
  section).
  + git
  + Emacs/Spacemacs

** Required Behaviors
   You are required to:
  + attend class, as assessments will happen in class each day that are not
    reproducible outside of class;
  + read assigned portions of the course materials /before/ class meetings when
    they will be discussed;
  + complete all team and personal assessments to deepen your understanding of
    selected topics; and
  + acquire and maintain a three-ring binder that will hold your portfolio of
    completed work (see below).

* Course Periodicity
  This course has a weekly period, i.e., you can count on knowing ahead of time
  what you will be doing each day of each week. Each class period consists of three
  30-minute sections.

  On Mondays these sections are:

  - Presentation :: --- A time where I will add depth information to the preparation
                    material you finished reading *before class*.
  - Class Directed Learning :: --- You will participate in a class-wide activity that
       reinforces what you\rsquo{}ve read and what I\rsquo{}ve shown you.
  - Create and Explain Solutions to Exercises :: --- During this time period, as
       a team of between three and five classmates you will create a solution to
       an exercise. On completion of your exercise you, as an individual, will
       explain your solution to someone not on your team until they understand
       your solution. Further information on this will be given in class.

  On Wednesdays these sections are:

  - Answer Questions :: --- I will answer questions that have been submitted to
       the class Slack workspace (more on which later --- but for now please
       [[https://join.slack.com/t/cs306s19/shared_invite/enQtNTk3NDk0MTQ4MTc4LTk5YzdhY2M3YjQyMWJkZjgwYzNjMDBiZGMyMDU4MDI3Mzk1ODQ2OWI0MDk2NTBkYjM0ODRhMGNkMzVlOGE5Y2I][click here to join]]).
  - Class Directed Learning :: --- You will participate in a class-wide activity that
       reinforces what you\rsquo{}ve read and what I\rsquo{}ve shown you.
  - Work Problems :: --- This is in-class time for individual work on the
                     assignment for the week. Successful students will have
                     started working on these problems *before* this half-hour.
* Questions
  + The questions answered on Wednesday are generalized from those you submit via
    the slack channel on Tuesday Evenings.
  + You must submit any and all unanswered questions on Tuesday evening. Not
    submitting questions leads to a reduced learning experience.
  + You will have plenty of questions. Submit them! Choose knowledge over
    ignorance.
* Work
** Exercises
   Exercises are smaller experiences that are designed to float uncertainties and
   questions you have to the surface of your mind. They are designed to be smaller
   so you can find out what you don\rsquo{}t know and then take the steps necessary to
   know.

** Problems
   Problems are weightier experiences that invite you to explore topics in
   algorithms and complexity, as well as increase your algorithmic problem
   solving prowess. All involve writing mathematically.

** Late Work
   Late work is accepted /only if/ the reason is extraordinary, and acceptance is
   reached through private and prolonged negotiation. Also, you must come talk to
   me in person in my office --- *NOT* by email, nor any other means of
   communication.
* Assessment
  About every four weeks you will meet with me in my office. The purpose of this
  meeting is for you to present your portfolio of work to me, make a grade-to-date
  claim, and provide evidence justifying that claim.

  Your portfolio *MUST* be a modified version of this file. All entries must
  follow the example format you will find at the end of this document (when it is
  updated). Also, your evidences must be complete and internally consistent. You
  are required to produce the portfolio using Spacemacs, export it as an HTML
  file (see how at the top of this file), and print it.
* Grades
  In each of our three personal meetings, you will present your portfolio and a
  letter-based grade-to-date claim. Afterwards I will give you my thoughts on the
  strength of your claim. The last claim that you make (not an average of the
  three), taking into account any feedback from me, will be your final grade for
  the course. All of your claims must must be evidence-based. That means you
  *MUST* bring the evidence with you, in your portfolio, that supports your claim.

** Letter-Based
   When making your claim, you are required to use the [[http://www.byui.edu/student-records/grades/grading-system][BYU-Idaho standard]]
   letter-based definition of grades, reproduced below:

   + \ldquo{}A\rdquo represents outstanding understanding, application, and integration of
     subject material and extensive evidence of original thinking, skillful use
     of concepts, and ability to analyze and solve complex problems.
     Demonstrates diligent application of Learning Model principles, including
     initiative in serving other students.
   + \ldquo{}B\rdquo represents considerable/significant understanding, application, and
     incorporation of the material that would prepare a student to be successful
     in next level courses, graduate school, or employment. The student
     participates in the Learning Model as applied in the course.
   + \ldquo{}C\rdquo represents sufficient understanding of subject matter. The student
     demonstrates minimal initiative to be prepared for class. Sequenced courses
     could be attempted, but mastering new materials might prove challenging.
     The student participates only marginally in the Learning Model.
   + \ldquo{}D\rdquo represents poor performance and initiative to learn and understand and
     apply course materials. Retaking a course or remediation may be necessary
     to prepare for additional instruction in this subject matter.
   + \ldquo{}F\rdquo represents failure in the course.

   Note that the above description of an \ldquo{}A\rdquo implies that you have gone *above and
   beyond*. To claim this grade you *must* have continually (not continuously) done
   one or both of the first two and one or both of the last two things listed below
   *each week* throughout the 4-week period, and you must also record evidence of
   these behaviors in your portfolio:
   1. teaching and/or helping others in the class but not in your group;
   2. teaching a Non-CS, Non-CE, Non-EE, Non-SE major about the material in this
      class to help them with a class they are taking;
   3. applying what you\rsquo{}ve learned in this class in another class you are
      currently taking; and
   4. doing work not assigned (such as puzzles --- see more on which later),
      exploring other topics in mathematics, writing code implementing what you
      are learning that has not been assigned, etc.

   Regarding the first two, quoting Truman Madsen (quoting the Prophet Joseph
   Smith): Now one of the strongest and wisest statements I have ever heard on
   egoism. The question was put to him, \ldquo{}Joseph, is the principle of
   self-aggrandizement wrong? Should we seek our own good?\rdquo Listen to his answer.
   \ldquo{}It is a correct principle and may be indulged upon only one rule or plan ---
   and that is to elevate, benefit, and bless others first. If you will elevate
   others, the very work itself will exalt you. Upon no other plan can a man justly
   and permanently aggrandize himself.\rdquo
* Legal
** Harassment
	 Title IX of the Education Amendments of 1972 prohibits sex discrimination
   against any participant in an education program or activity that receives
   federal funds, including Federal loans and grants. Title IX also covers
   student-to-student sexual harassment. If you encounter unlawful sexual
   harassment or gender based discrimination, please contact the Personnel Office
   at 208-496-1130.
** Disability
   Brigham Young University-Idaho is committed to providing a working and
   learning atmosphere which reasonably accommodates qualified persons with
   disabilities. If you have any disability which may impair your ability to
   complete this course successfully, please contact the Services for Students
   with Disabilities Office, 496-1158. Reasonable academic accommodations are
   reviewed for all students who have qualified documented disabilities. Services
   are coordinated with the student and instructor by this office. If you need
   assistance or if you feel you have been unlawfully discriminated against on
   the basis of disability, you may seek resolution through established grievance
   policy and procedures. You should contact the Personnel Office at 208-496-1130.
* Readings
  These readings are to be completed *before* each listed week\rsquo{}s Monday\rsquo{}s
  class.

  | Week | Reading from Textbook          |
  |------+--------------------------------|
  |   01 | Preface, Chapter 1, Appendix A |
  |   02 | Chapter 2, Appendix B          |
  |   03 | Chapter 3                      |
  |   04 | Chapter 4                      |
  |   05 | Chapter 5                      |
  |   06 | Chapter 6 sections 1-2         |
  |   07 | Chapter 6 sections 3, 5-6      |
  |   08 | Chapter 7                      |
  |   09 | Chapter 8                      |
  |   10 | Chapter 9                      |
  |   11 | Chapter 10                     |
  |   12 | Chapter 11                     |
  |   13 | Chapter 12                     |

* Portfolio
  Your portfolio consists of your Course Tracker together with Grade Claims and
  Evidences.
** Course Tracker Acronyms and Their Meanings
	+ CRU - I Completed the Reading and achieved a level of Understanding
          *before* the start of Monday\rsquo{}s class and recorded questions about the
          items I didn\rsquo{}t understand.
	+ PFP - I was present for and attentive to the presentation for this week.
	+ CDL - I fully participated in the Class Directed Learning for this day.
	+ SAQ - I, as the current representative of my team, submitted /at least 1/
    appropriate, Significant, Actual Question I have regarding the information
    for this week.
	+ PAQ - I was Present for and Attentive to the Answer Questions presentation for this week.
  + PPL - I, individually, correctly completed this Percentage of the Problems
    proving this Level of understanding before Monday at Midnight (for the
    previous week).
** Course Tracker Tables
   You are required to track your progress in the course using the tables below.
   Currently, you see full credit for week 0\rsquo{}s work. (\checkmark means yes. Blank means
   no.) Update the table for week 1 and all subsequent weeks each class day and
   week during the semester.

@@latex:\pagebreak@@
| / |   <> | <>  | <>  | <>  | <>  | <>  | <>  | <>   |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # | Week | CRU | PFP | CDL | SAQ | PAQ | CDL | PPL  |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |    0 | \check   | \check   | \check   | \check   | \check   | \check   | 100% |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |    1 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |    2 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |    3 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |    4 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|

  During week five, you will make your first claim by bringing this updated
  document to my office, where you will sign your name (in my presence) to the
  assertion below, and fill in your grade claim:

| / | <>                                                      | <>    | <>         |
|---+---------------------------------------------------------+-------+------------|
| # | The above table is an honest and true record of my work | Grade | Instructor |
| # | in this course for weeks one through four.              | Claim | Grade      |
|---+---------------------------------------------------------+-------+------------|
| # | Signed:                                                 |       |            |
| # |                                                         |       |            |
|---+---------------------------------------------------------+-------+------------|
@@html:<br /><br /><br />@@
@@latex:\pagebreak@@
| / |   <> | <>  | <>  | <>  | <>  | <>  | <>  | <>   |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # | Week | CRU | PFP | CDL | SAQ | PAQ | CDL | PPL  |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |    5 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |    6 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |    7 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |    8 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|

  During week nine, you will make your second claim by bringing this updated
  document to my office, where you will sign your name (in my presence) to the
  assertion below, and fill in your grade claim:

| / | <>                                                      | <>    | <>         |
|---+---------------------------------------------------------+-------+------------|
| # | The above table is an honest and true record of my work | Grade | Instructor |
| # | in this course for weeks five through eight.            | Claim | Grade      |
|---+---------------------------------------------------------+-------+------------|
| # | Signed:                                                 |       |            |
| # |                                                         |       |            |
|---+---------------------------------------------------------+-------+------------|
@@html:<br /><br /><br />@@
@@latex:\vspace{.5in}@@
| / |   <> | <>  | <>  | <>  | <>  | <>  | <>  | <>   |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # | Week | CRU | PFP | CDL | SAQ | PAQ | CDL | PPL  |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |    9 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |   10 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |   11 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |   12 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|
| # |   13 |     |     |     |     |     |     |      |
|---+------+-----+-----+-----+-----+-----+-----+------|

  During week fourteen, you will make your third and final claim by bringing this
  updated document to my office, where you will sign your name (in my presence) to
  the assertion below, and fill in your grade claim:

| / | <>                                                      | <>    | <>         |
|---+---------------------------------------------------------+-------+------------|
| # | The above table is an honest and true record of my work | Grade | Instructor |
| # | in this course for weeks nine through thirteen.         | Claim | Grade      |
|---+---------------------------------------------------------+-------+------------|
| # | Signed:                                                 |       |            |
| # |                                                         |       |            |
|---+---------------------------------------------------------+-------+------------|
@@html:<br /><br /><br />@@
@@latex:\pagebreak@@
* Evidences
  Fill in your evidences here each week to build your portfolio. The number of
  pieces of evidence are determined by you. However, the more you have the
  better off you will be.

:HINT:
  There is an extra \lsquo{}x\rsquo on the front of the INCLUDE directives below. Delete the
  \lsquo{}x\rsquo when the assignment file is in place, and put it back if you do not want
  that week exported.
:END:

** Week 1
#+xINCLUDE: ./assignment-01.org :only-contents t :lines "6-"
** Week 2
#+xINCLUDE: ./assignment-02.org :only-contents t :lines "6-"
** Week 3
#+xINCLUDE: ./assignment-03.org :only-contents t :lines "6-"
** Week 4
#+xINCLUDE: ./assignment-04.org :only-contents t :lines "6-"
** Week 5
#+xINCLUDE: ./assignment-05.org :only-contents t :lines "6-"
** Week 6
#+xINCLUDE: ./assignment-06.org :only-contents t :lines "6-"
** Week 7
#+xINCLUDE: ./assignment-07.org :only-contents t :lines "6-"
** Week 8
#+xINCLUDE: ./assignment-08.org :only-contents t :lines "6-"
** Week 9
#+xINCLUDE: ./assignment-09.org :only-contents t :lines "6-"
** Week 10
#+xINCLUDE: ./assignment-10.org :only-contents t :lines "6-"
** Week 11
#+xINCLUDE: ./assignment-11.org :only-contents t :lines "6-"
** Week 12
#+xINCLUDE: ./assignment-12.org :only-contents t :lines "6-"
** Week 13
#+xINCLUDE: ./assignment-13.org :only-contents t :lines "6-"

@@latex:\pagebreak@@
* Other
  This document may be modified by the instructor at any time without
  notification.
